// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//
// Long-lived browser tabs run a stale bundle after we deploy fixes that touch
// the work-queue executor (078 error propagation, 080 reclaim). When the frontend
// keeps polling /edgesonic/work/poll with the old buggy code, attempts++ until
// the deterministic-ID rows hit failed permanently.
//
// The SPA records the version on first load, polls /edgesonic/version every 5
// minutes, and shows a "new version available, refresh now" banner when the
// returned version differs. The banner is intentionally non-blocking — users
// can dismiss it for the session.
//
// Source of truth: the build-info.json asset bundled alongside the SPA. It is
// generated by vite.config.ts at build time and lives in web/dist, so it is
// always in sync with the loaded frontend bundle. We prefer it over env vars
// because `wrangler deploy --var` does not persist to the script's runtime
// env. EDGESONIC_VERSION / EDGESONIC_BUILD_TIME, if present, still win.
//
// Auth: this endpoint is in NO_AUTH_PATHS (worker/src/auth.ts) so the polling
// fetch works even after the session expires. The payload only exposes the
// build version and build time.
import { Hono } from "hono";
import { isDemoMode } from "../../utils/demoMode";

export const versionRoutes = new Hono<{ Bindings: Env }>();

async function readBuildInfoFromAsset(c: import("hono").Context<{ Bindings: Env }>): Promise<{ version?: string; buildTime?: string | null } | null> {
  // The ASSETS binding serves the exact static assets from this deployment.
  // It avoids a self-fetch through the Worker router and stays in lockstep
  // with the bundle constants used by main.ts.
  try {
    const url = new URL("/build-info.json", c.req.url);
    const r = await c.env.ASSETS.fetch(new Request(url));
    if (!r.ok) return null;
    return await r.json() as { version?: string; buildTime?: string | null };
  } catch {
    return null;
  }
}

versionRoutes.get("/version", async (c) => {
  const envVersion = c.env.EDGESONIC_VERSION;
  const envBuildTime = c.env.EDGESONIC_BUILD_TIME;
  // Prefer explicit env vars (operator override); fall back to the bundled
  // build-info.json asset which always matches the deployed frontend.
  if (envVersion) {
    return c.json({
      ok: true,
      version: envVersion,
      buildTime: envBuildTime || null,
      demoMode: isDemoMode(c.env),
    });
  }
  const asset = await readBuildInfoFromAsset(c);
  return c.json({
    ok: true,
    version: asset?.version || "dev",
    buildTime: asset?.buildTime || null,
    demoMode: isDemoMode(c.env),
  });
});
